### PR TITLE
Update VIA - timer, shift register, and CB transition detection fixes

### PR DESCRIPTION
**Pull request by gyurco**
These changes are verified in:
- VIC20, viavarious, via_sr and other misc tests from VICE. IFR tests
in via_sr are failing, because it expects timing on CA2 (cassette motor
input), which is affected by an external RC component.
- 1541 connected to C64: viavarious tests all pass
- BBC Micro: SD-Card adapter with heavy use of the shift register. It's
using an undocumented feautre: Mode 0 actually accepts input and loads the
shift register.

### CODE REVIEW

**Comment by gyurco** [comment]
Ah, sorry, I'll send it to upstream.

**Comment by markusC64** [comment]
If it is ok for you, we could test it anyway.

**Comment by gyurco** [comment]
Of course! I was actually confused which one is the more active repo.

**Comment by markusC64** [comment]
I already fetched your repository with git and merged it into a my branch v3.7-200406-markusC64 as new "testing" branch (not online).

**Pull request closed without merging**
